package itp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import com.sun.nio.fs.WindowsUserPrincipals.User;

 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHARUKH
 */


public class SalaryN extends javax.swing.JFrame {
    
    // Creates new form SalaryN
  
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    //PreparedStatement pst  = null;
   
    public SalaryN() {
  
        super("Salary");
        initComponents();
        show_salary();
        //conn = databaseConnection.connection();
    }
    
        
     public ArrayList<TSalary> teacherList(){
        
        ArrayList<TSalary> teacherList = new ArrayList<>();
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=tinytot;user=admin;password=123456");
            
            String query1 = "SELECT * FROM Teachers";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query1);
            TSalary salary;
            while(rs.next()){
                salary=new TSalary(rs.getString("Name") , rs.getInt("Id"), rs.getString("Designations") , rs.getInt("PresentDays"), rs.getString("Bank") , rs.getString("BankAccountNo")  ,  rs.getInt("BasicPay") , rs.getInt("OverTime") , rs.getInt("MedicalAllowance") , rs.getInt("DearnessAllowance") , rs.getInt("TotalEarnings") , rs.getInt("ProfessionalTax") , rs.getInt("ProvidentFund") , rs.getInt("Insurance") , rs.getInt("TotalDeductions") , rs.getInt("NetPay"));
                teacherList.add(salary);}                         
               }
                catch(Exception e){
                             JOptionPane.showMessageDialog(null,e);
                     }
        return teacherList;
    }
     
     public void show_salary(){
        ArrayList<TSalary> list = teacherList() ;
        DefaultTableModel model = (DefaultTableModel)St1.getModel();
        
        Object[] row = new Object[16];
            for(int i=0 ; i<list.size() ; i++){
                row[0]=list.get(i).getName();
                row[1]=list.get(i).getId();
                row[2]=list.get(i).getDesignation();
                row[3]=list.get(i).getPresentDays();
                row[4]=list.get(i).getBank();
                row[5]=list.get(i).getBankAccountNo();
                row[6]=list.get(i).getBasicPay();
                row[7]=list.get(i).getOverTime();
                row[8]=list.get(i).getMedicalAllowance();
                row[9]=list.get(i).getDearnessAllowance();
                row[10]=list.get(i).getTotalEarnings();
                row[11]=list.get(i).getProfessionalTax();
                row[12]=list.get(i).getProvidentFund();
                row[13]=list.get(i).getInsurance();
                row[14]=list.get(i).getTotalDeductions();
                row[15]=list.get(i).getNetPay();
                model.addRow(row);                                                                               
                     }
            }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        St1 = new javax.swing.JTable();
        Name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NetPay = new javax.swing.JTextField();
        TotalDeductions = new javax.swing.JTextField();
        Insurance = new javax.swing.JTextField();
        ProvidentFund = new javax.swing.JTextField();
        ProfessionalTax = new javax.swing.JTextField();
        TotalEarnings = new javax.swing.JTextField();
        DearnessAllowance = new javax.swing.JTextField();
        MedicalAllowance = new javax.swing.JTextField();
        OverTime = new javax.swing.JTextField();
        Sname12 = new javax.swing.JLabel();
        Sname11 = new javax.swing.JLabel();
        Sname10 = new javax.swing.JLabel();
        Sname9 = new javax.swing.JLabel();
        Sname8 = new javax.swing.JLabel();
        Sname7 = new javax.swing.JLabel();
        Sname6 = new javax.swing.JLabel();
        Sname5 = new javax.swing.JLabel();
        Sname4 = new javax.swing.JLabel();
        Sname3 = new javax.swing.JLabel();
        SINSERT = new javax.swing.JButton();
        SUPDATE = new javax.swing.JButton();
        SDELETE = new javax.swing.JButton();
        Sexit = new javax.swing.JButton();
        Bank = new javax.swing.JTextField();
        BankAccountNo = new javax.swing.JTextField();
        BasicPay = new javax.swing.JTextField();
        Sdesignation = new javax.swing.JLabel();
        SaccuntNo = new javax.swing.JLabel();
        Sbank = new javax.swing.JLabel();
        Designation = new javax.swing.JTextField();
        SpresentDays = new javax.swing.JLabel();
        PresentDays = new javax.swing.JTextField();
        Id = new javax.swing.JTextField();
        Sid = new javax.swing.JLabel();
        Stopic = new javax.swing.JLabel();
        Spanel1 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home-30.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(250, 670, 60, 40);

        St1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BasicPay", "OverTime", "Medical Allowance", "Dearness Allowance", "Total Earnings", "Professional Tax", "Provident Fund", "Insurance", "Total Deductions", "Net Pay"
            }
        ));
        jScrollPane2.setViewportView(St1);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 370, 1060, 270);

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        jPanel2.add(Name);
        Name.setBounds(170, 100, 150, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 100, 60, 22);

        NetPay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NetPayKeyTyped(evt);
            }
        });
        jPanel2.add(NetPay);
        NetPay.setBounds(920, 310, 150, 22);

        TotalDeductions.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TotalDeductionsKeyTyped(evt);
            }
        });
        jPanel2.add(TotalDeductions);
        TotalDeductions.setBounds(920, 280, 150, 22);

        Insurance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InsuranceKeyTyped(evt);
            }
        });
        jPanel2.add(Insurance);
        Insurance.setBounds(920, 250, 150, 22);

        ProvidentFund.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ProvidentFundKeyTyped(evt);
            }
        });
        jPanel2.add(ProvidentFund);
        ProvidentFund.setBounds(920, 220, 150, 22);

        ProfessionalTax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ProfessionalTaxKeyTyped(evt);
            }
        });
        jPanel2.add(ProfessionalTax);
        ProfessionalTax.setBounds(920, 190, 150, 22);

        TotalEarnings.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TotalEarningsKeyTyped(evt);
            }
        });
        jPanel2.add(TotalEarnings);
        TotalEarnings.setBounds(920, 160, 150, 22);

        DearnessAllowance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DearnessAllowanceKeyTyped(evt);
            }
        });
        jPanel2.add(DearnessAllowance);
        DearnessAllowance.setBounds(920, 130, 150, 22);

        MedicalAllowance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MedicalAllowanceKeyTyped(evt);
            }
        });
        jPanel2.add(MedicalAllowance);
        MedicalAllowance.setBounds(920, 100, 150, 22);

        OverTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                OverTimeKeyTyped(evt);
            }
        });
        jPanel2.add(OverTime);
        OverTime.setBounds(170, 310, 150, 22);

        Sname12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Sname12.setForeground(new java.awt.Color(255, 255, 255));
        Sname12.setText("Basic Pay");
        jPanel2.add(Sname12);
        Sname12.setBounds(10, 280, 120, 20);

        Sname11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Sname11.setForeground(new java.awt.Color(255, 255, 255));
        Sname11.setText("OverTime");
        jPanel2.add(Sname11);
        Sname11.setBounds(10, 310, 120, 20);

        Sname10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Sname10.setForeground(new java.awt.Color(255, 255, 255));
        Sname10.setText("Medical Allowance");
        jPanel2.add(Sname10);
        Sname10.setBounds(710, 100, 150, 20);

        Sname9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Sname9.setForeground(new java.awt.Color(255, 255, 255));
        Sname9.setText("Dearness Allowance");
        jPanel2.add(Sname9);
        Sname9.setBounds(710, 130, 160, 20);

        Sname8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Sname8.setForeground(new java.awt.Color(255, 255, 255));
        Sname8.setText("Total Earnings");
        jPanel2.add(Sname8);
        Sname8.setBounds(710, 160, 120, 20);

        Sname7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Sname7.setForeground(new java.awt.Color(255, 255, 255));
        Sname7.setText("Provident Fund");
        jPanel2.add(Sname7);
        Sname7.setBounds(710, 220, 120, 20);

        Sname6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Sname6.setForeground(new java.awt.Color(255, 255, 255));
        Sname6.setText("Total Deductions");
        jPanel2.add(Sname6);
        Sname6.setBounds(710, 280, 150, 20);

        Sname5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Sname5.setForeground(new java.awt.Color(255, 255, 255));
        Sname5.setText("Net Pay");
        jPanel2.add(Sname5);
        Sname5.setBounds(710, 310, 120, 20);

        Sname4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Sname4.setForeground(new java.awt.Color(255, 255, 255));
        Sname4.setText("Insurance");
        jPanel2.add(Sname4);
        Sname4.setBounds(710, 250, 120, 20);

        Sname3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Sname3.setForeground(new java.awt.Color(255, 255, 255));
        Sname3.setText("Professional Tax");
        jPanel2.add(Sname3);
        Sname3.setBounds(710, 190, 150, 20);

        SINSERT.setBackground(new java.awt.Color(153, 153, 255));
        SINSERT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insert-30.png"))); // NOI18N
        SINSERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SINSERTActionPerformed(evt);
            }
        });
        jPanel2.add(SINSERT);
        SINSERT.setBounds(10, 670, 60, 40);

        SUPDATE.setBackground(new java.awt.Color(153, 153, 255));
        SUPDATE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update-30.png"))); // NOI18N
        SUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUPDATEActionPerformed(evt);
            }
        });
        jPanel2.add(SUPDATE);
        SUPDATE.setBounds(90, 670, 60, 40);

        SDELETE.setBackground(new java.awt.Color(153, 153, 255));
        SDELETE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete-30.png"))); // NOI18N
        SDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SDELETEActionPerformed(evt);
            }
        });
        jPanel2.add(SDELETE);
        SDELETE.setBounds(170, 670, 63, 39);

        Sexit.setBackground(new java.awt.Color(153, 153, 255));
        Sexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/color-home-30.png"))); // NOI18N
        Sexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SexitActionPerformed(evt);
            }
        });
        jPanel2.add(Sexit);
        Sexit.setBounds(1000, 670, 60, 40);
        jPanel2.add(Bank);
        Bank.setBounds(170, 220, 150, 20);

        BankAccountNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BankAccountNoKeyTyped(evt);
            }
        });
        jPanel2.add(BankAccountNo);
        BankAccountNo.setBounds(170, 250, 150, 20);

        BasicPay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BasicPayKeyTyped(evt);
            }
        });
        jPanel2.add(BasicPay);
        BasicPay.setBounds(170, 280, 150, 22);

        Sdesignation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Sdesignation.setForeground(new java.awt.Color(255, 255, 255));
        Sdesignation.setText("Designation");
        jPanel2.add(Sdesignation);
        Sdesignation.setBounds(10, 160, 150, 20);

        SaccuntNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SaccuntNo.setForeground(new java.awt.Color(255, 255, 255));
        SaccuntNo.setText("Bank Account No");
        jPanel2.add(SaccuntNo);
        SaccuntNo.setBounds(10, 250, 150, 22);

        Sbank.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Sbank.setForeground(new java.awt.Color(255, 255, 255));
        Sbank.setText("Bank");
        jPanel2.add(Sbank);
        Sbank.setBounds(10, 220, 110, 20);
        jPanel2.add(Designation);
        Designation.setBounds(170, 160, 150, 22);

        SpresentDays.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SpresentDays.setForeground(new java.awt.Color(255, 255, 255));
        SpresentDays.setText("Present Days");
        jPanel2.add(SpresentDays);
        SpresentDays.setBounds(10, 190, 150, 20);

        PresentDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresentDaysActionPerformed(evt);
            }
        });
        PresentDays.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PresentDaysKeyTyped(evt);
            }
        });
        jPanel2.add(PresentDays);
        PresentDays.setBounds(170, 190, 150, 22);

        Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdActionPerformed(evt);
            }
        });
        jPanel2.add(Id);
        Id.setBounds(170, 130, 150, 20);

        Sid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Sid.setForeground(new java.awt.Color(255, 255, 255));
        Sid.setText("Id");
        jPanel2.add(Sid);
        Sid.setBounds(10, 130, 90, 20);

        Stopic.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Stopic.setForeground(new java.awt.Color(255, 255, 255));
        Stopic.setText("Pay Slip For Month Of September 2019");
        jPanel2.add(Stopic);
        Stopic.setBounds(60, 0, 980, 80);

        Spanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        Spanel1.setText("jLabel15");
        jPanel2.add(Spanel1);
        Spanel1.setBounds(0, 0, 1080, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PresentDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresentDaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PresentDaysActionPerformed

    private void IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdActionPerformed

    
    
     
    
    private void SINSERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SINSERTActionPerformed
        // TODO add your handling code here:
        
       String name1 = Name.getText();
       String id1 = Id.getText();
       String designation1 = Designation.getText();
       String presentDays1 = PresentDays.getText();
       String bank1 = Bank.getText();
       String accountNo1 = BankAccountNo.getText();
       String basicPay1 = BasicPay.getText();
       String overTime1 = OverTime.getText();
       String medical1 = MedicalAllowance.getText();
       String dearness1 = DearnessAllowance.getText();
       String totalEarnings1 = TotalEarnings.getText();
       String professional1 = ProfessionalTax.getText();
       String provident1 = ProvidentFund.getText();
       String insurance1 = Insurance.getText();
       String totalDeducions1 = TotalDeductions.getText();
       String netPay1 = NetPay.getText();
   
       
       if(name1.equals("")){
           JOptionPane.showMessageDialog(null,"Name field is empty");
       }
        else if(id1.equals("")){
           JOptionPane.showMessageDialog(null,"ID field is empty");
       }
       else if(designation1.equals("")){
           JOptionPane.showMessageDialog(null,"Designation field is empty");
       }
       else if(presentDays1.equals("")){
           JOptionPane.showMessageDialog(null,"Present Days field is empty");
       }
       else if(bank1.equals("")){
           JOptionPane.showMessageDialog(null,"Bank field is empty");
       }
       else if(accountNo1.equals("")){
           JOptionPane.showMessageDialog(null,"Bank AccountNo field is empty");
       }
       else if(basicPay1.equals("")){
           JOptionPane.showMessageDialog(null,"Basic Pay field is empty");
       }
       else if(overTime1.equals("")){
           JOptionPane.showMessageDialog(null,"OverTime field is empty");
       }
       else if(medical1.equals("")){
           JOptionPane.showMessageDialog(null,"Medical Allowance field is empty");
       }
       else if(dearness1.equals("")){
           JOptionPane.showMessageDialog(null,"Darness Allowance field is empty");
       }
       else if(totalEarnings1.equals("")){
           JOptionPane.showMessageDialog(null,"Total Earnings field is empty");
       }
       else if(professional1.equals("")){
           JOptionPane.showMessageDialog(null,"Professional Tax field is empty");
       }
       else if(provident1.equals("")){
           JOptionPane.showMessageDialog(null,"Provident Fund field is empty");
       }
       else if(insurance1.equals("")){
           JOptionPane.showMessageDialog(null,"Insurance field is empty");
       }
       else if(totalDeducions1.equals("")){
           JOptionPane.showMessageDialog(null,"Total Deductions field is empty");
       }
        else if(netPay1.equals("")){
           JOptionPane.showMessageDialog(null,"Net Pay field is empty");
       }
       else{
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=tinytot;user=admin;password=123456");
            String query ="insert into Teachers(Name,Id,Designations,PresentDays,Bank,BankAccountNo,BasicPay,OverTime,MedicalAllowance,DearnessAllowance,TotalEarnings,ProfessionalTax,ProvidentFund,Insurance,TotalDeductions,NetPay)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = conn.prepareStatement(query);
            
                    pst.setString(1 ,Name.getText());
                    pst.setString(2 ,Id.getText());
                    pst.setString(3 ,Designation.getText());
                    pst.setString(4 ,PresentDays.getText());
                    pst.setString(5 ,Bank.getText());
                    pst.setString(6 ,BankAccountNo.getText());
                    pst.setString(7 ,BasicPay.getText());
                    pst.setString(8 ,OverTime.getText()); 
                    pst.setString(9 ,MedicalAllowance.getText());
                    pst.setString(10 ,DearnessAllowance.getText());
                    pst.setString(11 ,TotalEarnings.getText());
                    pst.setString(12 ,ProfessionalTax.getText());
                    pst.setString(13 ,ProvidentFund.getText());
                    pst.setString(14 ,Insurance.getText());
                    pst.setString(15 ,TotalDeductions.getText());
                    pst.setString(16 ,NetPay.getText());
                    
                  pst.executeUpdate();
                  DefaultTableModel model = (DefaultTableModel)St1.getModel();
                  model.setRowCount(0);
                  show_salary();
                  JOptionPane.showMessageDialog(null,"Inserted Successfully!");
                 
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
      }
    }//GEN-LAST:event_SINSERTActionPerformed
  }   
    
    private void SUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUPDATEActionPerformed
        // TODO add your handling code here:
       String name1 = Name.getText();
       String id1 = Id.getText();
       String designation1 = Designation.getText();
       String presentDays1 = PresentDays.getText();
       String bank1 = Bank.getText();
       String accountNo1 = BankAccountNo.getText();
       String basicPay1 = BasicPay.getText();
       String overTime1 = OverTime.getText();
       String medical1 = MedicalAllowance.getText();
       String dearness1 = DearnessAllowance.getText();
       String totalEarnings1 = TotalEarnings.getText();
       String professional1 = ProfessionalTax.getText();
       String provident1 = ProvidentFund.getText();
       String insurance1 = Insurance.getText();
       String totalDeducions1 = TotalDeductions.getText();
       String netPay1 = NetPay.getText();
   
       
       if(name1.equals("")){
           JOptionPane.showMessageDialog(null,"Name field is empty");
       }
       else if(id1.equals("")){
           JOptionPane.showMessageDialog(null,"ID field is empty");
       }       
       else if(designation1.equals("")){
           JOptionPane.showMessageDialog(null,"Designation field is empty");
       }
       else if(presentDays1.equals("")){
           JOptionPane.showMessageDialog(null,"Present Days field is empty");
       }
       else if(bank1.equals("")){
           JOptionPane.showMessageDialog(null,"Bank field is empty");
       }
       else if(accountNo1.equals("")){
           JOptionPane.showMessageDialog(null,"Bank AccountNo field is empty");
       }
       else if(basicPay1.equals("")){
           JOptionPane.showMessageDialog(null,"Basic Pay field is empty");
       }
       else if(overTime1.equals("")){
           JOptionPane.showMessageDialog(null,"OverTime field is empty");
       }
       else if(medical1.equals("")){
           JOptionPane.showMessageDialog(null,"Medical Allowance field is empty");
       }
       else if(dearness1.equals("")){
           JOptionPane.showMessageDialog(null,"Darness Allowance field is empty");
       }
       else if(totalEarnings1.equals("")){
           JOptionPane.showMessageDialog(null,"Total Earnings field is empty");
       }
       else if(professional1.equals("")){
           JOptionPane.showMessageDialog(null,"Professional Tax field is empty");
       }
       else if(provident1.equals("")){
           JOptionPane.showMessageDialog(null,"Provident Fund field is empty");
       }
       else if(insurance1.equals("")){
           JOptionPane.showMessageDialog(null,"Insurance field is empty");
       }
       else if(totalDeducions1.equals("")){
           JOptionPane.showMessageDialog(null,"Total Deductions field is empty");
       }
        else if(netPay1.equals("")){
           JOptionPane.showMessageDialog(null,"Net Pay field is empty");
       }
       else{
     
            
            try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=tinytot;user=admin;password=123456");
            
            int row = St1.getSelectedRow();
            String value = (St1.getModel().getValueAt(row, 0).toString());
            String query = "UPDATE Teachers set Name=? , Designation=? , PresentDays=? , Bank=?  , BankAccountNo=? , BasicPay=? , OverTime=? , MedicalAllowance=? , DearnessAllowance=? , TotalEarnings=? , ProfessionalTax=? , ProvidentFund=? , Insurance=? , TotalDeductions=? ,NetPay=? where Id="+value;
            PreparedStatement pst = conn.prepareStatement(query);  
            
                    pst.setString(1 ,Name.getText());
//                    pst.setString(2 ,Id.getText());
                    pst.setString(2 ,Designation.getText());
                    pst.setString(3 ,PresentDays.getText());
                    pst.setString(4 ,Bank.getText());
                    pst.setString(5 ,BankAccountNo.getText());
                    pst.setString(6 , BasicPay.getText());
                    pst.setString(7 ,OverTime.getText()); 
                    pst.setString(8 ,MedicalAllowance.getText());
                    pst.setString(9 ,DearnessAllowance.getText());
                    pst.setString(10 ,TotalEarnings.getText());
                    pst.setString(11 ,ProfessionalTax.getText());
                    pst.setString(12 ,ProvidentFund.getText());
                    pst.setString(13 ,Insurance.getText());
                    pst.setString(14 ,TotalDeductions.getText());
                    pst.setString(15 ,NetPay.getText());
                    
                  pst.executeUpdate();
                  DefaultTableModel model = (DefaultTableModel)St1.getModel();
                  model.setRowCount(0);
                  show_salary();
                  JOptionPane.showMessageDialog(null,"Inserted Successfully!");
                
     }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
           }
        }
    }//GEN-LAST:event_SUPDATEActionPerformed

    
    
    
    private void SDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SDELETEActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "DO you really want to delete?");
        
        if(x==0){
               String id1 = Id.getText();
               
                if(id1.equals("")){
                        JOptionPane.showConfirmDialog(null, "ID is required");
                }
                else{
                    String sql = "DELETE from Teachers where name1 = '" + id1 +"'";
               
        
          try{
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=tinytot;user=admin;password=123456");
     
            int row = St1.getSelectedRow();
            String value = (St1.getModel().getValueAt(row,0).toString());
            String query = "DELETE FROM Teachers where Id="+value;
            PreparedStatement pst = conn.prepareStatement(query);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)St1.getModel();
            model.setRowCount(0);
             show_salary();
            JOptionPane.showMessageDialog(null,"Delete Successfully!");
        
          }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
              }
           }
        }
    }//GEN-LAST:event_SDELETEActionPerformed

    private void SexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SexitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SexitActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        HomeN home = new HomeN();
//        home.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PresentDaysKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PresentDaysKeyTyped
char c = evt.getKeyChar();
        if(Character.isLetter(c) && !evt.isAltDown() )
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_PresentDaysKeyTyped

    private void BankAccountNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BankAccountNoKeyTyped
char c = evt.getKeyChar();
        if(Character.isLetter(c) && !evt.isAltDown() )
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BankAccountNoKeyTyped

    private void BasicPayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BasicPayKeyTyped
char c = evt.getKeyChar();
        if(Character.isLetter(c) && !evt.isAltDown() )
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BasicPayKeyTyped

    private void OverTimeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OverTimeKeyTyped
char c = evt.getKeyChar();
        if(Character.isLetter(c) && !evt.isAltDown() )
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_OverTimeKeyTyped

    private void MedicalAllowanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MedicalAllowanceKeyTyped
char c = evt.getKeyChar();
        if(Character.isLetter(c) && !evt.isAltDown() )
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_MedicalAllowanceKeyTyped

    private void DearnessAllowanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DearnessAllowanceKeyTyped
char c = evt.getKeyChar();
        if(Character.isLetter(c) && !evt.isAltDown() )
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_DearnessAllowanceKeyTyped

    private void TotalEarningsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TotalEarningsKeyTyped
char c = evt.getKeyChar();
        if(Character.isLetter(c) && !evt.isAltDown() )
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_TotalEarningsKeyTyped

    private void ProfessionalTaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProfessionalTaxKeyTyped
char c = evt.getKeyChar();
        if(Character.isLetter(c) && !evt.isAltDown() )
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_ProfessionalTaxKeyTyped

    private void ProvidentFundKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProvidentFundKeyTyped
char c = evt.getKeyChar();
        if(Character.isLetter(c) && !evt.isAltDown() )
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_ProvidentFundKeyTyped

    private void InsuranceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InsuranceKeyTyped
char c = evt.getKeyChar();
        if(Character.isLetter(c) && !evt.isAltDown() )
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_InsuranceKeyTyped

    private void TotalDeductionsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TotalDeductionsKeyTyped
char c = evt.getKeyChar();
        if(Character.isLetter(c) && !evt.isAltDown() )
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_TotalDeductionsKeyTyped

    private void NetPayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NetPayKeyTyped
char c = evt.getKeyChar();
        if(Character.isLetter(c) && !evt.isAltDown() )
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_NetPayKeyTyped
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaryN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaryN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaryN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaryN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalaryN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bank;
    private javax.swing.JTextField BankAccountNo;
    private javax.swing.JTextField BasicPay;
    private javax.swing.JTextField DearnessAllowance;
    private javax.swing.JTextField Designation;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Insurance;
    private javax.swing.JTextField MedicalAllowance;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField NetPay;
    private javax.swing.JTextField OverTime;
    private javax.swing.JTextField PresentDays;
    private javax.swing.JTextField ProfessionalTax;
    private javax.swing.JTextField ProvidentFund;
    private javax.swing.JButton SDELETE;
    private javax.swing.JButton SINSERT;
    private javax.swing.JButton SUPDATE;
    private javax.swing.JLabel SaccuntNo;
    private javax.swing.JLabel Sbank;
    private javax.swing.JLabel Sdesignation;
    private javax.swing.JButton Sexit;
    private javax.swing.JLabel Sid;
    private javax.swing.JLabel Sname10;
    private javax.swing.JLabel Sname11;
    private javax.swing.JLabel Sname12;
    private javax.swing.JLabel Sname3;
    private javax.swing.JLabel Sname4;
    private javax.swing.JLabel Sname5;
    private javax.swing.JLabel Sname6;
    private javax.swing.JLabel Sname7;
    private javax.swing.JLabel Sname8;
    private javax.swing.JLabel Sname9;
    private javax.swing.JLabel Spanel1;
    private javax.swing.JLabel SpresentDays;
    private javax.swing.JTable St1;
    private javax.swing.JLabel Stopic;
    private javax.swing.JTextField TotalDeductions;
    private javax.swing.JTextField TotalEarnings;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    

}
