/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Lidushan
 */
public class Search extends javax.swing.JFrame {

    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jStudentId = new javax.swing.JTextField();
        class_select = new javax.swing.JComboBox<>();
        term_select = new javax.swing.JComboBox<>();
        searchBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        btn_addAS = new javax.swing.JButton();
        btn_searchAS = new javax.swing.JButton();
        btn_deleteAS = new javax.swing.JButton();
        btn_updateAS = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Progress Card");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1024, 720));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Student ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 210, 94, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Class:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(480, 260, 48, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Term:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 300, 49, 20);

        jStudentId.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(jStudentId);
        jStudentId.setBounds(550, 200, 283, 33);

        class_select.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        class_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LKG", "UKG" }));
        class_select.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(class_select);
        class_select.setBounds(550, 250, 147, 33);

        term_select.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        term_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        term_select.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(term_select);
        term_select.setBounds(550, 300, 147, 33);

        searchBtn.setBackground(new java.awt.Color(0, 153, 153));
        searchBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        searchBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lidushan\\Desktop\\GUIimages\\search.png")); // NOI18N
        searchBtn.setText("SEARCH");
        searchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn);
        searchBtn.setBounds(550, 360, 150, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lidushan\\Desktop\\GUIimages\\kin.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(600, 460, 400, 226);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("VIEW STUDENT PROGRESS CARD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(247, 0, 780, 110);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lidushan\\Desktop\\GUIimages\\back.png")); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 210, 49, 57);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setBackground(new java.awt.Color(255, 255, 255));
        btn_home.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btn_home.setText("   Home");
        btn_home.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_home.setBorderPainted(false);
        btn_home.setContentAreaFilled(false);
        btn_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_home.setFocusPainted(false);
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel7.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, -1));

        btn_addAS.setBackground(new java.awt.Color(255, 255, 255));
        btn_addAS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_addAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btn_addAS.setText("   Add Details");
        btn_addAS.setBorder(null);
        btn_addAS.setBorderPainted(false);
        btn_addAS.setContentAreaFilled(false);
        btn_addAS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_addAS.setFocusPainted(false);
        btn_addAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addASActionPerformed(evt);
            }
        });
        jPanel7.add(btn_addAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 50));

        btn_searchAS.setBackground(new java.awt.Color(255, 255, 255));
        btn_searchAS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_searchAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-find-user-male-40(1).png"))); // NOI18N
        btn_searchAS.setText("   Search Details");
        btn_searchAS.setBorder(null);
        btn_searchAS.setBorderPainted(false);
        btn_searchAS.setContentAreaFilled(false);
        btn_searchAS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_searchAS.setFocusPainted(false);
        btn_searchAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchASActionPerformed(evt);
            }
        });
        jPanel7.add(btn_searchAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 200, 40));

        btn_deleteAS.setBackground(new java.awt.Color(255, 255, 255));
        btn_deleteAS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_deleteAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delet.png"))); // NOI18N
        btn_deleteAS.setText("   Delete details");
        btn_deleteAS.setBorder(null);
        btn_deleteAS.setBorderPainted(false);
        btn_deleteAS.setContentAreaFilled(false);
        btn_deleteAS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_deleteAS.setFocusPainted(false);
        btn_deleteAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteASActionPerformed(evt);
            }
        });
        jPanel7.add(btn_deleteAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 200, 40));

        btn_updateAS.setBackground(new java.awt.Color(255, 255, 255));
        btn_updateAS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_updateAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btn_updateAS.setText("   Update details");
        btn_updateAS.setBorder(null);
        btn_updateAS.setBorderPainted(false);
        btn_updateAS.setContentAreaFilled(false);
        btn_updateAS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_updateAS.setFocusPainted(false);
        btn_updateAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateASActionPerformed(evt);
            }
        });
        jPanel7.add(btn_updateAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 200, -1));

        btn_exit.setBackground(new java.awt.Color(255, 255, 255));
        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btn_exit.setText("   Exit");
        btn_exit.setBorder(null);
        btn_exit.setBorderPainted(false);
        btn_exit.setContentAreaFilled(false);
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.setFocusPainted(false);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel7.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 100, 40));

        getContentPane().add(jPanel7);
        jPanel7.setBounds(0, 0, 249, 720);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(370, 490, 69, 22);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(810, 300, 64, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        try{
            Connection con = null;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionURL= "jdbc:sqlserver://localhost:1433;databaseName=newDB;user=sa; password=skyline404";
        
            con = DriverManager.getConnection(connectionURL);
        
            String query; 
            query = "select * from progressCard where st_id = ? AND class = ? AND term = ?";
            
            
            PreparedStatement pst = con.prepareStatement(query);
            
            pst.setString(1, jStudentId.getText());
            pst.setString(2, class_select.getSelectedItem().toString());
            pst.setString(3, term_select.getSelectedItem().toString());
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                
            /*newSearch newS = new newSearch();
            setVisible(true);*/
            
            
            jTextField1.setText(rs.getString("st_name"));
            
            
            
            
            
            }
            
            
           
            
            jStudentId.setText("");
            class_select.setSelectedIndex(0);
            term_select.setSelectedIndex(0);
            
            
            
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_searchBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new MainMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed

        setVisible(false);

        MainMenu home = new MainMenu();
        home.setVisible(true);
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_addASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addASActionPerformed

        setVisible(false);

        LKG addas = new LKG();
        addas.setVisible(true);
    }//GEN-LAST:event_btn_addASActionPerformed

    private void btn_searchASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchASActionPerformed

        setVisible(false);

        Search searchas = new Search();
        searchas.setVisible(true);
    }//GEN-LAST:event_btn_searchASActionPerformed

    private void btn_deleteASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteASActionPerformed

        setVisible(false);

        Delete deleteas = new Delete();
        deleteas.setVisible(true);
    }//GEN-LAST:event_btn_deleteASActionPerformed

    private void btn_updateASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateASActionPerformed

        setVisible(false);

        Edit updateas = new Edit();
        updateas.setVisible(true);
    }//GEN-LAST:event_btn_updateASActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed

        int returnValue = 0;
        returnValue = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Are you sure?", JOptionPane.YES_NO_OPTION);

        if (returnValue == JOptionPane.YES_OPTION)
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addAS;
    private javax.swing.JButton btn_deleteAS;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_searchAS;
    private javax.swing.JButton btn_updateAS;
    private javax.swing.JComboBox<String> class_select;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jStudentId;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox<String> term_select;
    // End of variables declaration//GEN-END:variables
}
