package itp;


import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class StudentEarlyLeaveDisplay extends javax.swing.JFrame {
    /**
     * Creates new form StudentEarlyLeaveDisplay
     */
   
    public StudentEarlyLeaveDisplay() {
        initComponents();
        try {
            show_user();
        } catch (SQLException ex) {
            Logger.getLogger(StudentEarlyLeaveDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    public ArrayList<User> userList() throws SQLException{
        ArrayList<User> userList = new ArrayList<>();
        
        dbConnection db = new dbConnection();
        Connection conn = db.getConnection();
        
        String query1 = "SELECT * FROM studentEarlyLeave";
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(query1);
        User user;
        
        while(rs.next()){
            user = new User(rs.getString("studentID"), rs.getString("date"), rs.getString("guardianName"), rs.getString("nic"), rs.getString("contactNo"),rs.getString("address"),rs.getString("reason"));
            userList.add(user);
        }
        
        
        return userList;
        
    }
    
    public void show_user() throws SQLException{
        ArrayList<User> list =  userList();
        DefaultTableModel model = (DefaultTableModel)jTable_Display_User.getModel();
        Object[] row = new Object[7];
        for(int i=0; i <list.size();i++){
                row[0]=list.get(i).getStudentID();
                row[1]=list.get(i).getDate();
                row[2]=list.get(i).getGuardianName();
                row[3]=list.get(i).getNic();
                row[4]=list.get(i).getContactNo();
                row[5]=list.get(i).getAddress();
                row[6]=list.get(i).getReason();
            
                model.addRow(row);
                }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        dateCh = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_genAS = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        studentID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        delete_btn = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_User = new javax.swing.JTable();
        demobtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 720));
        getContentPane().setLayout(null);

        dateCh.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(dateCh);
        dateCh.setBounds(370, 590, 240, 20);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(null);

        btn_home.setBackground(new java.awt.Color(255, 255, 255));
        btn_home.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-page-40.png"))); // NOI18N
        btn_home.setText("   Home");
        btn_home.setBorder(null);
        btn_home.setBorderPainted(false);
        btn_home.setContentAreaFilled(false);
        btn_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_home.setFocusPainted(false);
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel7.add(btn_home);
        btn_home.setBounds(50, 40, 130, 40);

        btn_exit.setBackground(new java.awt.Color(255, 255, 255));
        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-ios-40.png"))); // NOI18N
        btn_exit.setText("   Exit");
        btn_exit.setBorder(null);
        btn_exit.setBorderPainted(false);
        btn_exit.setContentAreaFilled(false);
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.setFocusPainted(false);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel7.add(btn_exit);
        btn_exit.setBounds(60, 240, 100, 40);

        btn_genAS.setBackground(new java.awt.Color(255, 255, 255));
        btn_genAS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_genAS.setText("Generate Report");
        btn_genAS.setBorder(null);
        btn_genAS.setBorderPainted(false);
        btn_genAS.setContentAreaFilled(false);
        btn_genAS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_genAS.setFocusPainted(false);
        btn_genAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_genASActionPerformed(evt);
            }
        });
        jPanel7.add(btn_genAS);
        btn_genAS.setBounds(20, 110, 220, 40);

        btn_back.setBackground(new java.awt.Color(255, 255, 255));
        btn_back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-arrow-46.png"))); // NOI18N
        btn_back.setText("   Back");
        btn_back.setBorder(null);
        btn_back.setBorderPainted(false);
        btn_back.setContentAreaFilled(false);
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.setFocusPainted(false);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel7.add(btn_back);
        btn_back.setBounds(50, 170, 130, 40);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(0, 0, 260, 720);
        getContentPane().add(studentID);
        studentID.setBounds(410, 460, 150, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 470, 70, 30);

        delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-delete-user-male-40.png"))); // NOI18N
        delete_btn.setText("   Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        getContentPane().add(delete_btn);
        delete_btn.setBounds(840, 630, 150, 40);

        btn_edit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-update-30.png"))); // NOI18N
        btn_edit.setText("    Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit);
        btn_edit.setBounds(620, 630, 140, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 550, 80, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/9.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(630, 410, 370, 210);

        date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateKeyReleased(evt);
            }
        });
        getContentPane().add(date);
        date.setBounds(410, 540, 150, 40);

        jTable_Display_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StudentID", "Date", "Guardian Name", "NIC", "Contact No", "Address", "Reason"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Display_User);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 0, 770, 390);

        demobtn.setBackground(new java.awt.Color(204, 204, 204));
        demobtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        demobtn.setForeground(new java.awt.Color(51, 51, 51));
        demobtn.setText("DEMO");
        demobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demobtnActionPerformed(evt);
            }
        });
        getContentPane().add(demobtn);
        demobtn.setBounds(290, 630, 130, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(260, 390, 760, 330);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        this.setVisible(false);
        homePage home = new homePage();
        home.setVisible(true);
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        int returnValue = 0;
        returnValue = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Are you sure?", JOptionPane.YES_NO_OPTION);
        
        if(returnValue == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        dbConnection db = new dbConnection();
        Connection conn = db.getConnection();
        
        if(studentID.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter a Student ID!!");
        }
       
        String sql1 = "delete from studentEarlyLeave where studentID = ? AND date = ?";
        try {
            PreparedStatement pst1 = conn.prepareStatement(sql1);
               
            pst1.setString(1, studentID.getText());
            pst1.setString(2, date.getText());
           
            pst1.executeUpdate();

            JOptionPane.showMessageDialog(null, "Successfully deleted");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
     
        // TODO add your handling code here:
        this.setVisible(false);
       
        try {
            StudentEaryLeavingEdit editleave  = new StudentEaryLeavingEdit(studentID.getText(), date.getText());
            
            editleave.setVisible(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(StudentEarlyLeaveDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
        
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_genASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_genASActionPerformed
          int rowno = 0;
        try {
        dbConnection db = new dbConnection();
        Connection conn = db.getConnection();
        
        Statement st = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        ResultSet rs = st.executeQuery("Select * from studentEarlyLeave");
        
        ResultSetMetaData rsmd = rs.getMetaData();
        int colno = rsmd.getColumnCount();
        
            while(rs.next())
            {
                rowno = rowno+1;
            }
        rs.first();

        com.itextpdf.text.Document d = new com.itextpdf.text.Document(PageSize.A4.rotate(), 0, 0, 0, 0);
        try {
            try {
                PdfWriter.getInstance(d, new FileOutputStream("Student Early Leaving Detials.pdf"));
            } catch (DocumentException ex) {
                Logger.getLogger(StudentEarlyLeaveDisplay.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(StudentEarlyLeaveDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        PdfPTable pt = new PdfPTable(colno);
        
        d.open();
        
                try {
                    d.add(new Paragraph("\n\n Student Early Leaving Detials  \n\n\n"));
                } catch (DocumentException ex) {
                    Logger.getLogger(StudentEarlyLeaveDisplay.class.getName()).log(Level.SEVERE, null, ex);
                }
        
            
            pt.addCell("StudentID");
            pt.addCell("Date");
            pt.addCell("Guardian Name");
            pt.addCell("NIC");
            pt.addCell("Contact No");
            pt.addCell("Address");
            pt.addCell("Reason");
       
        for(int i=0; i<rowno;i++){
                    pt.addCell(""+rs.getString(1));
                    pt.addCell(""+rs.getString(2));
                    pt.addCell(""+rs.getString(3));
                    pt.addCell(""+rs.getString(4));
                    pt.addCell(""+rs.getString(5));
                    pt.addCell(""+rs.getString(6));
                    pt.addCell(""+rs.getString(7));
                    
            rs.next();
        }
       
        
                try {
                    d.add(pt);
                } catch (DocumentException ex) {
                    Logger.getLogger(StudentEarlyLeaveDisplay.class.getName()).log(Level.SEVERE, null, ex);
                }
        
        d.close();
        
        JOptionPane.showMessageDialog(null, "Report Gegerated Successfully!");
        
        } catch (SQLException ex) {
            Logger.getLogger(StudentEarlyLeaveDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_genASActionPerformed

    private void demobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demobtnActionPerformed
        // TODO add your handling code here:
        studentID.setText("1");
        date.setText("2019-10-04");
    }//GEN-LAST:event_demobtnActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new StudentEaryLeaving().setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    private void dateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateKeyReleased
        // TODO add your handling code here:
        //String PATTERN = "^(0?[1-9]|[12][0-9]|3[01])[\\/\\-](0?[1-9]|1[012])[\\/\\-]\\d{4}$";
        String PATTERN1 = "^\\d{4}[\\/\\-](0?[1-9]|1[012])[\\/\\-](0?[1-9]|[12][0-9]|3[01])$";
        
        Pattern patt = Pattern.compile(PATTERN1);
        Matcher match = patt.matcher(date.getText());
        if(!match.matches()){
            dateCh.setText("Incorrect Date(example-2019-02-03)");
        }
        else{
            dateCh.setText(null);
        }
    }//GEN-LAST:event_dateKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentEarlyLeaveDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentEarlyLeaveDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentEarlyLeaveDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentEarlyLeaveDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentEarlyLeaveDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_genAS;
    private javax.swing.JButton btn_home;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField date;
    private javax.swing.JLabel dateCh;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton demobtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_User;
    private javax.swing.JTextField studentID;
    // End of variables declaration//GEN-END:variables
}
