package itp;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Maneesha
 */
public class StudentAttendanceDisplay extends javax.swing.JFrame { 
    /**
     * Creates new form StudentAttendanceDisplay
     */
    public StudentAttendanceDisplay() throws SQLException {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_genAS = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableAttendanceStudent = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        show_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        presentStudentsL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1024, 720));
        getContentPane().setLayout(null);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(null);

        btn_home.setBackground(new java.awt.Color(255, 255, 255));
        btn_home.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-page-40.png"))); // NOI18N
        btn_home.setText("   Home");
        btn_home.setBorder(null);
        btn_home.setBorderPainted(false);
        btn_home.setContentAreaFilled(false);
        btn_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_home.setFocusPainted(false);
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel7.add(btn_home);
        btn_home.setBounds(50, 40, 130, 40);

        btn_exit.setBackground(new java.awt.Color(255, 255, 255));
        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-ios-40.png"))); // NOI18N
        btn_exit.setText("   Exit");
        btn_exit.setBorder(null);
        btn_exit.setBorderPainted(false);
        btn_exit.setContentAreaFilled(false);
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.setFocusPainted(false);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel7.add(btn_exit);
        btn_exit.setBounds(70, 210, 100, 40);

        btn_genAS.setBackground(new java.awt.Color(255, 255, 255));
        btn_genAS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_genAS.setText("Generate Report");
        btn_genAS.setBorder(null);
        btn_genAS.setBorderPainted(false);
        btn_genAS.setContentAreaFilled(false);
        btn_genAS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_genAS.setFocusPainted(false);
        btn_genAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_genASActionPerformed(evt);
            }
        });
        jPanel7.add(btn_genAS);
        btn_genAS.setBounds(20, 100, 220, 40);

        btn_back.setBackground(new java.awt.Color(255, 255, 255));
        btn_back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-arrow-46.png"))); // NOI18N
        btn_back.setText("   Back");
        btn_back.setBorder(null);
        btn_back.setBorderPainted(false);
        btn_back.setContentAreaFilled(false);
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.setFocusPainted(false);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel7.add(btn_back);
        btn_back.setBounds(50, 150, 140, 40);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(0, 0, 260, 720);

        jtableAttendanceStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "StudentID", "Name", "Present/Absent"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtableAttendanceStudent);
        if (jtableAttendanceStudent.getColumnModel().getColumnCount() > 0) {
            jtableAttendanceStudent.getColumnModel().getColumn(0).setResizable(false);
            jtableAttendanceStudent.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(320, 190, 630, 500);

        jPanel1.setBackground(new java.awt.Color(153, 0, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Student Attendance Display");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(260, 0, 770, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Date    :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(660, 120, 80, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background-2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 150, 770, 570);

        date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        date.setMaxSelectableDate(new java.util.Date(2177433000000L));
        date.setMinSelectableDate(new java.util.Date(1546281000000L));
        getContentPane().add(date);
        date.setBounds(730, 110, 150, 40);

        show_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        show_button.setText("Show");
        show_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(show_button);
        show_button.setBounds(900, 110, 110, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Present Students :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 120, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("A B C D E F G H I J K L M N O P Q R S T U V W X Y Z");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 40, 730, 80);

        presentStudentsL.setBackground(new java.awt.Color(0, 0, 0));
        presentStudentsL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(presentStudentsL);
        presentStudentsL.setBounds(420, 110, 70, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        setVisible(false);
        homePage home = new homePage();
        home.setVisible(true);
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        setVisible(false);
        StudentAttendance sa = new StudentAttendance();
        sa.setVisible(true);       
    }//GEN-LAST:event_btn_exitActionPerformed

    private void show_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_buttonActionPerformed
        int presentStudents = 0;
        
        String date2 = new SimpleDateFormat("MMM d, yyyy").format(date.getDate() );
        try {
            ArrayList<AttendanceDis> attendanceList = new ArrayList<>();
            
            dbConnection db = new dbConnection();
            Connection conn = db.getConnection();
            
            String query = "select * from attendance where date = '"+date2+"'";
            
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);
            AttendanceDis attendanceDis;
            
            String check = "p";
            
            while(rs.next()){
                attendanceDis = new AttendanceDis(rs.getDate("date"),rs.getString("studentID"),  rs.getString("name"), rs.getString("present_absent"));
                
                String checkA = rs.getString("present_absent");
                if(check.equals(checkA))
                {
                    presentStudents = presentStudents+ 1;
                }
                attendanceList.add(attendanceDis);
            }
           
            DefaultTableModel model = (DefaultTableModel)jtableAttendanceStudent.getModel();
            Object[] row = new Object[5];
            for(int i=0; i <attendanceList.size();i++){
                row[0]=attendanceList.get(i).getDate();           
                row[1]=attendanceList.get(i).getStudentID();
                row[2]=attendanceList.get(i).getName();
                row[3]=attendanceList.get(i).getPresent_absent();
         
                model.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentAttendanceDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        presentStudentsL.setText(String.valueOf(presentStudents));
        
    }//GEN-LAST:event_show_buttonActionPerformed

    private void btn_genASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_genASActionPerformed
            int rowno = 0;
        try {
        dbConnection db = new dbConnection();
        Connection conn = db.getConnection();
        
        Statement st = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        ResultSet rs = st.executeQuery("Select * from attendance");
        
        ResultSetMetaData rsmd = rs.getMetaData();
        int colno = rsmd.getColumnCount();
    
            while(rs.next()){            
                rowno = rowno+1;
            }
        rs.first();

        com.itextpdf.text.Document d = new com.itextpdf.text.Document(PageSize.A4.rotate(), 0, 0, 0, 0);
        try {
            try {
                PdfWriter.getInstance(d, new FileOutputStream("Student Attendance Detials.pdf"));
            } catch (DocumentException ex) {
                Logger.getLogger(StudentAttendanceDisplay.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(asPDFReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        PdfPTable pt = new PdfPTable(colno);
        
        d.open();
        
            try {
                d.add(new Paragraph("\n\n Student Attendance Details \n\n\n"));
            } catch (DocumentException ex) {
                Logger.getLogger(StudentAttendanceDisplay.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        pt.addCell("DATE");
        pt.addCell("StudentID");
        pt.addCell("Firnt Name");
        pt.addCell("Present/Absent");
       
        for(int i=0; i<rowno;i++){
            pt.addCell(""+rs.getString(1));
                    pt.addCell(""+rs.getString(2));
                    pt.addCell(""+rs.getString(3));
                    pt.addCell(""+rs.getString(4));
            rs.next();
        }
                try {
                    d.add(pt);
                } catch (DocumentException ex) {
                    Logger.getLogger(StudentAttendanceDisplay.class.getName()).log(Level.SEVERE, null, ex);
                }
        
        d.close();
        
        JOptionPane.showMessageDialog(null, "Report Gegerated Successfully!");
        
        } catch (SQLException ex) {
            Logger.getLogger(StudentAttendanceDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_genASActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new StudentAttendance().setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentAttendanceDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentAttendanceDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentAttendanceDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentAttendanceDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new StudentAttendanceDisplay().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(StudentAttendanceDisplay.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_genAS;
    private javax.swing.JButton btn_home;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableAttendanceStudent;
    private javax.swing.JLabel presentStudentsL;
    private javax.swing.JButton show_button;
    // End of variables declaration//GEN-END:variables
}
