/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itp;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.text.*;
import java.time.LocalDateTime;
import java.util.logging.*;
import java.util.regex.Pattern;
import javax.swing.*;

/**
 *
 * @author thishantj
 */
public class studentDetails extends javax.swing.JFrame {

    /**
     * Creates new form studentDetails
     */
    public studentDetails() {
        initComponents();
        jPanel5.setBackground(new Color(0,51,204,101));
        jPanel7.setBackground(new Color(0,51,204,101));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1_generalDetails = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel_parentName = new javax.swing.JLabel();
        parentName = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        jLabel_tel = new javax.swing.JLabel();
        jLabel_address = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jLabel_email = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel_personalDetails = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel_firstName = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        jLabel_lastName = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        jLabel_dob = new javax.swing.JLabel();
        studentID = new javax.swing.JTextField();
        jLabel_studentID = new javax.swing.JLabel();
        dobPicker = new com.toedter.calendar.JDateChooser();
        jPanel8 = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_searchS = new javax.swing.JButton();
        btn_deleteS = new javax.swing.JButton();
        btn_report = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_updateS1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(226, 226, 226));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Student Management System");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 70));

        jPanel7.setBackground(new java.awt.Color(0, 0, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1_generalDetails.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1_generalDetails.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1_generalDetails.setText("General details");
        jPanel7.add(jLabel1_generalDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 280, 90));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_parentName.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        jLabel_parentName.setForeground(new java.awt.Color(132, 132, 132));
        jLabel_parentName.setText("Parent's name");
        jPanel9.add(jLabel_parentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        parentName.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jPanel9.add(parentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 310, 50));

        tel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telKeyTyped(evt);
            }
        });
        jPanel9.add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 310, 50));

        jLabel_tel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        jLabel_tel.setForeground(new java.awt.Color(132, 132, 132));
        jLabel_tel.setText("Contact number");
        jPanel9.add(jLabel_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel_address.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        jLabel_address.setForeground(new java.awt.Color(132, 132, 132));
        jLabel_address.setText("Address");
        jPanel9.add(jLabel_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        address.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jPanel9.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 310, 50));

        btn_save.setBackground(new java.awt.Color(204, 255, 255));
        btn_save.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-save-40.png"))); // NOI18N
        btn_save.setText("Save");
        btn_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel9.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 130, -1));

        btn_clear.setBackground(new java.awt.Color(255, 183, 183));
        btn_clear.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-clear-symbol-40.png"))); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel9.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 130, -1));

        jLabel_email.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        jLabel_email.setForeground(new java.awt.Color(132, 132, 132));
        jLabel_email.setText("Email");
        jPanel9.add(jLabel_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        email.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jPanel9.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 310, 50));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 370, 590));

        jPanel5.setBackground(new java.awt.Color(0, 0, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_personalDetails.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_personalDetails.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel_personalDetails.setText("Personal details");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel_personalDetails)
                .addGap(35, 35, 35))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel_personalDetails)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 280, 90));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_firstName.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        jLabel_firstName.setForeground(new java.awt.Color(132, 132, 132));
        jLabel_firstName.setText("First name");
        jPanel10.add(jLabel_firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lastName.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jPanel10.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 310, 50));

        jLabel_lastName.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        jLabel_lastName.setForeground(new java.awt.Color(132, 132, 132));
        jLabel_lastName.setText("Last name");
        jPanel10.add(jLabel_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        firstName.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jPanel10.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 310, 50));

        jLabel_dob.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        jLabel_dob.setForeground(new java.awt.Color(132, 132, 132));
        jLabel_dob.setText("Date of birth");
        jPanel10.add(jLabel_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        studentID.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        studentID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studentIDKeyTyped(evt);
            }
        });
        jPanel10.add(studentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 310, 50));

        jLabel_studentID.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        jLabel_studentID.setForeground(new java.awt.Color(132, 132, 132));
        jLabel_studentID.setText("Student ID");
        jPanel10.add(jLabel_studentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        dobPicker.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        dobPicker.setMaxSelectableDate(new java.util.Date(1419967867000L));
        dobPicker.setMinSelectableDate(new java.util.Date(852058867000L));
        jPanel10.add(dobPicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 310, 50));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 370, 590));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setBackground(new java.awt.Color(255, 255, 255));
        btn_home.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-page-40.png"))); // NOI18N
        btn_home.setText("   Home");
        btn_home.setBorder(null);
        btn_home.setBorderPainted(false);
        btn_home.setContentAreaFilled(false);
        btn_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_home.setFocusPainted(false);
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel8.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, -1));

        btn_add.setBackground(new java.awt.Color(255, 255, 255));
        btn_add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-user-male-40(1).png"))); // NOI18N
        btn_add.setText("   Add student");
        btn_add.setBorder(null);
        btn_add.setBorderPainted(false);
        btn_add.setContentAreaFilled(false);
        btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_add.setFocusPainted(false);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel8.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 180, 50));

        btn_searchS.setBackground(new java.awt.Color(255, 255, 255));
        btn_searchS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_searchS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-find-user-male-40(1).png"))); // NOI18N
        btn_searchS.setText("   Search student");
        btn_searchS.setBorder(null);
        btn_searchS.setBorderPainted(false);
        btn_searchS.setContentAreaFilled(false);
        btn_searchS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_searchS.setFocusPainted(false);
        btn_searchS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchSActionPerformed(evt);
            }
        });
        jPanel8.add(btn_searchS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 200, 40));

        btn_deleteS.setBackground(new java.awt.Color(255, 255, 255));
        btn_deleteS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_deleteS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-delete-user-male-40.png"))); // NOI18N
        btn_deleteS.setText("   Delete student");
        btn_deleteS.setBorder(null);
        btn_deleteS.setBorderPainted(false);
        btn_deleteS.setContentAreaFilled(false);
        btn_deleteS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_deleteS.setFocusPainted(false);
        btn_deleteS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteSActionPerformed(evt);
            }
        });
        jPanel8.add(btn_deleteS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 200, 40));

        btn_report.setBackground(new java.awt.Color(255, 255, 255));
        btn_report.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-graph-report-40.png"))); // NOI18N
        btn_report.setText("   Generate report");
        btn_report.setBorder(null);
        btn_report.setBorderPainted(false);
        btn_report.setContentAreaFilled(false);
        btn_report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_report.setFocusPainted(false);
        btn_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportActionPerformed(evt);
            }
        });
        jPanel8.add(btn_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 210, -1));

        btn_logout.setBackground(new java.awt.Color(255, 255, 255));
        btn_logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-ios-40.png"))); // NOI18N
        btn_logout.setText("   Logout");
        btn_logout.setBorder(null);
        btn_logout.setBorderPainted(false);
        btn_logout.setContentAreaFilled(false);
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.setFocusPainted(false);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel8.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 130, 40));

        btn_updateS1.setBackground(new java.awt.Color(255, 255, 255));
        btn_updateS1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_updateS1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-change-user-40.png"))); // NOI18N
        btn_updateS1.setText("   Update student");
        btn_updateS1.setBorder(null);
        btn_updateS1.setBorderPainted(false);
        btn_updateS1.setContentAreaFilled(false);
        btn_updateS1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_updateS1.setFocusPainted(false);
        btn_updateS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateS1ActionPerformed(evt);
            }
        });
        jPanel8.add(btn_updateS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 200, -1));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 250, 650));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        setSize(new java.awt.Dimension(1098, 767));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
       
        firstName.setText("");
        lastName.setText("");
        dobPicker.setDate(null);
        parentName.setText("");
        tel.setText("");
        address.setText("");
        email.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void studentIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentIDKeyTyped
        
        char c = evt.getKeyChar();
        
        if(Character.isLetter(c) && !evt.isAltDown() )
        {
            evt.consume();
        }
    }//GEN-LAST:event_studentIDKeyTyped

    private void telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telKeyTyped
        
        char c = evt.getKeyChar();
        
        if(Character.isLetter(c) && !evt.isAltDown() )
        {
            evt.consume();
        }
    }//GEN-LAST:event_telKeyTyped

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed

//        loginForm l = new loginForm();
//        if(l.getType().toString().equalsIgnoreCase("administrator"))
//        {
            homePage home = new homePage();
            home.setVisible(true);
            this.setVisible(false);
//        }
//        if(l.getType().toString().equalsIgnoreCase("teacher"))
//        {
//            teacherHomePage thome = new teacherHomePage();
//            thome.setVisible(true);
//            this.setVisible(false);
//        }
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed

        studentDetails std = new studentDetails();
        std.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_searchSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchSActionPerformed

        searchStudent searchstd = new searchStudent();
        searchstd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_searchSActionPerformed

    private void btn_deleteSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteSActionPerformed

        deleteStudent deletestd = new deleteStudent();
        deletestd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_deleteSActionPerformed

    private void btn_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportActionPerformed

        studentReport r = new studentReport();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_reportActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed

        loginForm lf = new loginForm();
        lf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
          
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=tinytot;user=admin;password=123456");
            
            if(email.getText().isEmpty() || studentID.getText().isEmpty() || firstName.getText().isEmpty() || lastName.getText().isEmpty() ||  parentName.getText().isEmpty() || tel.getText().isEmpty() || address.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter missing fields", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if(studentID.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter a student ID", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if(firstName.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter a first name", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if(lastName.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter a last name", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if(dobPicker.getDate().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Please enter a date of birth");
            }
            else if(parentName.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter a parent's name", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if(tel.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter a telephone number", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if(address.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter an address", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if(email.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter an email", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email.getText()))) 
            {

                JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
            
            String query = "insert into students(studentID, fname, lname, dob, parentName, tel, address, email) values(?,?,?,?,?,?,?,?)";
            
            PreparedStatement pst = conn.prepareStatement(query);
            
            pst.setString(1, studentID.getText() );
            pst.setString(2, firstName.getText() );
            pst.setString(3, lastName.getText() );
            pst.setString(4, new SimpleDateFormat("MMM d, yyyy").format(dobPicker.getDate() ) );
            pst.setString(5, parentName.getText() );
            pst.setString(6, tel.getText() );
            pst.setString(7, address.getText() );
            pst.setString(8, email.getText() );
           
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Successfully inserted");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_updateS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateS1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex );  
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_deleteS;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_report;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_searchS;
    private javax.swing.JButton btn_updateS1;
    private com.toedter.calendar.JDateChooser dobPicker;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_generalDetails;
    private javax.swing.JLabel jLabel_address;
    private javax.swing.JLabel jLabel_dob;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_firstName;
    private javax.swing.JLabel jLabel_lastName;
    private javax.swing.JLabel jLabel_parentName;
    private javax.swing.JLabel jLabel_personalDetails;
    private javax.swing.JLabel jLabel_studentID;
    private javax.swing.JLabel jLabel_tel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField parentName;
    private javax.swing.JTextField studentID;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
